// Code generated by "stringer -type=Name"; DO NOT EDIT.

package app

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FlowFramework-0]
	_ = x[RubixWires-1]
	_ = x[PiGpio-2]
	_ = x[Broker-3]
	_ = x[LoraService-4]
	_ = x[None-5]
}

const _Name_name = "FlowFrameworkRubixWiresPiGpioBrokerLoraServiceNone"

var _Name_index = [...]uint8{0, 13, 23, 29, 35, 46, 50}

func (i Name) String() string {
	if i < 0 || i >= Name(len(_Name_index)-1) {
		return "Name(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Name_name[_Name_index[i]:_Name_index[i+1]]
}
