// Code generated by "stringer -type=Name"; DO NOT EDIT.

package app

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[flowFramework-0]
	_ = x[rubixWires-1]
	_ = x[piGpio-2]
	_ = x[broker-3]
	_ = x[loraService-4]
}

const _Name_name = "flowFrameworkrubixWirespiGpiobrokerloraService"

var _Name_index = [...]uint8{0, 13, 23, 29, 35, 46}

func (i Name) String() string {
	if i < 0 || i >= Name(len(_Name_index)-1) {
		return "Name(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Name_name[_Name_index[i]:_Name_index[i+1]]
}
