database:
  driver: sqlite
  name: data.db
  log:
    store: false
    level: info # silent, error, warn, info
server:
  log:
    store: false
    level: info # panic, fatal, error, warn, info, debugG, trace
gin:
  log:
    store: false
    level: debug # debug, release, test