// Code generated by "stringer -type=ActionType"; DO NOT EDIT.

package apps

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[start-0]
	_ = x[stop-1]
	_ = x[status-2]
	_ = x[enable-3]
	_ = x[disable-4]
	_ = x[isRunning-5]
	_ = x[isInstalled-6]
	_ = x[isEnabled-7]
	_ = x[isActive-8]
	_ = x[isFailed-9]
}

const _ActionType_name = "startstopstatusenabledisableisRunningisInstalledisEnabledisActiveisFailed"

var _ActionType_index = [...]uint8{0, 5, 9, 15, 21, 28, 37, 48, 57, 65, 73}

func (i ActionType) String() string {
	if i < 0 || i >= ActionType(len(_ActionType_index)-1) {
		return "ActionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionType_name[_ActionType_index[i]:_ActionType_index[i+1]]
}
